---
name: "Java + Maven + Docker"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: "${{ secrets.GH_TOKEN }}"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set up JDK 24"
      uses: "actions/setup-java@v4"
      with:
        distribution: "zulu"
        java-version: "24"
        java-package: "jdk"
        cache: "maven"
    - name: "Set up Maven"
      uses: "stCarolas/setup-maven@v5"
      with:
        maven-version: "3.9.9"
    - run: "make M='mvn -s settings.xml' fmtCheck"
    - run: "make M='mvn -s settings.xml'"
